version: "3"

services:
  openpredict-api:
    container_name: openpredict-api
    build: .
    # image: docker.pkg.github.com/maastrichtu-ids/translator-openpredict/openpredict-api:latest
    # image: umids/openpredict-api:latest
    restart: unless-stopped
    # command: compute-similarities
    command: start-api --server-url https://openpredict.137.120.31.102.nip.io
    ports:
      - 8808:8808
    environment: 
      # Variable for nginx-proxy routing
      VIRTUAL_HOST: openpredict.137.120.31.102.nip.io
      LETSENCRYPT_HOST: openpredict.137.120.31.102.nip.io
      VIRTUAL_PORT: 8808
    # volumes:
    #   - ./data:/data
