version: "3"

services:

  openpredict-api:
    container_name: openpredict-api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    restart: unless-stopped
    ports:
      - 8808:8808
      - 8000:8000
    volumes:
      - ./data:/data/openpredict
      - ./openpredict:/root/openpredict
    environment:
      - PYTHONUNBUFFERED=1
    ## Use Connexion:
    # entrypoint: openpredict start-api --debug
    ## Use FastAPI:
    entrypoint: uvicorn openpredict.app:app --host 0.0.0.0 --reload


    #   SPARQL_USERNAME: ${SPARQL_USERNAME}
    #   SPARQL_PASSWORD: ${SPARQL_PASSWORD}
    #   SPARQL_ENDPOINT_URL: https://graphdb.dumontierlab.com/repositories/translator-openpredict-dev
    #   SPARQL_ENDPOINT_UPDATE_URL: https://graphdb.dumontierlab.com/repositories/translator-openpredict-dev/statements

      # OPENPREDICT_APIKEY: ${OPENPREDICT_APIKEY}

  # openpredict-virtuoso:
  #   container_name: openpredict-virtuoso
  #   image: 'tenforce/virtuoso:latest'
  #   environment:
  #     DBA_PASSWORD: dba
  #     SPARQL_UPDATE: 'true'
  #     DEFAULT_GRAPH: 'https://w3id.org/openpredict/graph'
  #   volumes:
  #     - './data/virtuoso:/data'
  #   ports:
  #     - '8890:8890'
  #     - '1111:1111'