version: "3"

services:
  openpredict-api:
    container_name: openpredict-api
    build: .
    # Outdated image: docker.pkg.github.com/maastrichtu-ids/translator-openpredict/openpredict-api:latest
    # Outdated image: umids/openpredict-api:latest
    restart: unless-stopped
    # command: train-model
    command: start-api --server-url https://openpredict.137.120.31.102.nip.io
    ports:
      - 8808:8808
    environment: 
      OPENPREDICT_USERNAME: ${OPENPREDICT_USERNAME}
      OPENPREDICT_PASSWORD: ${OPENPREDICT_PASSWORD}
      PYSPARK_PYTHON: /opt/conda/bin/python3
      PYSPARK_DRIVER_PYTHON: /opt/conda/bin/python3
      # Variable for nginx-proxy routing. See https://github.com/nginx-proxy/
      VIRTUAL_HOST: openpredict.137.120.31.102.nip.io
      LETSENCRYPT_HOST: openpredict.137.120.31.102.nip.io
      VIRTUAL_PORT: 8808
    # volumes:
    #   - ./data:/data
