version: "3"
services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    ports:
      - 8808:8808
    volumes:
      - ./:/app
    environment:
      # Show print() in logs:
      PYTHONUNBUFFERED: '1'
      DEV_MODE: 'true'

      # SPARQL_ENDPOINT_URL: https://graphdb.dumontierlab.com/repositories/translator-openpredict
      # SPARQL_ENDPOINT_UPDATE_URL: https://graphdb.dumontierlab.com/repositories/translator-openpredict/statements

    entrypoint: uvicorn openpredict.main:app --host 0.0.0.0 --port 8808 --reload
    # entrypoint: openpredict start-api --debug
    ## Gunicorn for multiple uvicorn workers in prod:
    # entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8808 openpredict.main:app


  test:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    volumes:
      - ./:/app
    environment:
      # Show print() in logs:
      PYTHONUNBUFFERED: '1'
      DEV_MODE: 'true'
    entrypoint: pytest --cov=src
