version: "3"

services:
  sut:
    build: .
    command: pip install pytest && pytest tests
    environment: 
      PYSPARK_PYTHON: /opt/conda/bin/python3
      PYSPARK_DRIVER_PYTHON: /opt/conda/bin/python3
