version: '3'
services:
  api:
    build: .
    
    # environment: 
    #   SPARQL_USERNAME: ${SPARQL_USERNAME}
    #   SPARQL_PASSWORD: ${SPARQL_PASSWORD}
    #   SPARQL_ENDPOINT_URL: https://graphdb.dumontierlab.com/repositories/translator-openpredict
    #   SPARQL_ENDPOINT_UPDATE_URL: https://graphdb.dumontierlab.com/repositories/translator-openpredict/statements

      # OPENPREDICT_APIKEY: ${OPENPREDICT_APIKEY}
      # SPARK_MASTER_URL: spark://my-spark-spark-master:7077

