version: "3"

services:
  openpredict-virtuoso:
    container_name: openpredict-virtuoso
    image: 'tenforce/virtuoso:latest'
    environment:
      DBA_PASSWORD: dba
      SPARQL_UPDATE: 'true'
      DEFAULT_GRAPH: 'https://w3id.org/openpredict/graph'
    volumes:
      - './data/virtuoso:/data'
    ports:
      - '8890:8890'
      - '1111:1111'