version: "3"
services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    ports:
      - 8808:8808
      - 8000:8000
    volumes:
      - ./data:/data/openpredict
      - ./openpredict:/app/openpredict
      - ./tests:/app/tests
    environment:
      # Show print() in logs:
      PYTHONUNBUFFERED: '1'
      DEV_MODE: 'true'

      # SPARQL_ENDPOINT_URL: https://graphdb.dumontierlab.com/repositories/translator-openpredict
      # SPARQL_ENDPOINT_UPDATE_URL: https://graphdb.dumontierlab.com/repositories/translator-openpredict/statements
    
    entrypoint: uvicorn openpredict.main:app --host 0.0.0.0 --port 8808 --reload
    # entrypoint: openpredict start-api --debug
    ## Gunicorn for multiple uvicorn workers in prod:
    # entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8808 openpredict.main:app



    #   SPARQL_USERNAME: ${SPARQL_USERNAME}
    #   SPARQL_PASSWORD: ${SPARQL_PASSWORD}
    #   SPARQL_ENDPOINT_URL: https://graphdb.dumontierlab.com/repositories/translator-openpredict-dev
    #   SPARQL_ENDPOINT_UPDATE_URL: https://graphdb.dumontierlab.com/repositories/translator-openpredict-dev/statements

      # OPENPREDICT_APIKEY: ${OPENPREDICT_APIKEY}

  # openpredict-virtuoso:
  #   container_name: openpredict-virtuoso
  #   image: 'tenforce/virtuoso:latest'
  #   environment:
  #     DBA_PASSWORD: dba
  #     SPARQL_UPDATE: 'true'
  #     DEFAULT_GRAPH: 'https://w3id.org/openpredict/graph'
  #   volumes:
  #     - './data/virtuoso:/data'
  #   ports:
  #     - '8890:8890'
  #     - '1111:1111'