[tool.poetry]
name = "openpredict"
version = "0.1.0"
description = "An API to compute and serve predictions of biomedical concepts associations via OpenAPI for the NCATS Translator project"
authors = ["Vincent Emonet <vincent.emonet@gmail.com>"]

# package_data={'': ['openapi.yml', 'data/models/*', 'data/ontology/*', 'data/models/*',
#         'data/features/*', 'data/input/*', 'data/sparql/*', 'data/resources/*', 'data/*.ttl',
#         'tests/queries/*', 'data/embedding/*']},

# packages = [{ include = "schema_graph" }]
include = [
  'openapi.yml', 'data/models/*', 'data/ontology/*', 'data/models/*',
  'data/features/*', 'data/input/*', 'data/sparql/*', 'data/resources/*', 'data/*.ttl',
  'tests/queries/*', 'data/embedding/*'
]

[tool.poetry.scripts]
openpredict = "openpredict.__main__:main"

[tool.poetry.dependencies]
python = ">=3.8,<3.10"
# click==7.1.2
click = "*"
python-multipart = "^0.0.5"
requests = "^2.23.0"
httpx = "^0.21.1"
pydantic = "^1.9"
reasoner-pydantic = "^2.2.3"
# reasoner-pydantic = "^3.0.0 "
fastapi = "^0.68.1"
uvicorn = "^0.15.0"
gunicorn = "^20.0.4"
Authlib = "^0.15.4"
itsdangerous = "^2.0.1"
rdflib = "^6.1.1"
joblib = "*"
numpy = "==1.16.1"
scipy = "==1.5.4"
# scipy==0.19.1
## Cannot update to numpy1.16.5 because it requires werkzeug>=2.0
# numpy==1.16.5
# werkzeug>=2.0
pandas = "==1.1.1"
# pandas==1.2.4
cython = "*"
pyspark = "==3.1.1"
findspark = "*"
scikit-learn = "==0.23.1"
SPARQLWrapper = ">=2.0.0,<3.0.0"
networkx = "*"
gensim = "==3.8.3"
shap = "*"
matplotlib = "*"
torch = "*"
# To load from local path for development
# nanopub = {path = "/opt/nanopub", develop = true}
# nanopub = {path = "../../nanopub", develop = true}


[tool.poetry.dev-dependencies]
reasoner-validator = ">=2.2.4,<3"
# reasoner-validator = "^3.0.0"
mypy = "=0.770"
# black = "^22.3.0"
black = "^21.12b0"
click = "=8.0.2"
# Pin click dependency to fix version conflict between reasoner-validator and black
isort = "^5.0.6"
autoflake = "^1.3.1"
flake8 = "^3.7.9"
pytest = "^5.4.1"
pytest-cov = "^2.8.1"
coverage = "*"
trio = "^0.19.0"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
line_length = 120
profile = "black"
# known_third_party = ["fastapi", "pydantic", "starlette"]

[tool.mypy]
plugins = [
  "pydantic.mypy"
]
ignore_missing_imports = true
# warn_return_any = true
# warn_unused_configs = true
# disallow_untyped_defs = true
# strict = true

# [[tool.mypy.overrides]]
# module = "fastapi.concurrency"
# warn_unused_ignores = false
# ignore_missing_imports = true

# [[tool.mypy.overrides]]
# module = "tests.*"
# ignore_missing_imports = true
# check_untyped_defs = true

# [tool.pytest.ini_options]
# addopts = [
#   "--strict-config",
#   "--strict-markers",
# ]
# xfail_strict = true
# junit_family = "xunit2"
# filterwarnings = [
#     "error",
#     'ignore:The loop argument is deprecated since Python 3\.8, and scheduled for removal in Python 3\.10:DeprecationWarning:asyncio',
#     'ignore:starlette.middleware.wsgi is deprecated and will be removed in a future release\..*:DeprecationWarning:starlette',
# ]


[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
