name: Python Package using Conda
# Publish to PyPI when new release on GitHub, if tests pass
on:
  workflow_dispatch:
  release:
    types: [ created ]
  # push:
  #   branches: [ master ]

jobs:
  tests-conda:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        $CONDA/bin/conda env update --file environment.yml --name base
    - name: Test with pytest
      run: |
        conda install pytest
        $CONDA/bin/pytest

    ## We could also setup the conda command instead of Python
    ## https://github.com/marketplace/actions/setup-conda
    # - name: Setup conda
    #   uses: s-weigand/setup-conda@v1
    #   with:
    #     update-conda: true
    #     python-version: ${{ matrix.python-version }}
    #     conda-channels: anaconda, conda-forge

  ## Publish to Conda forge?
  # https://github.com/marketplace/actions/publish-conda
  # publish-conda:
  #   needs: [ tests-conda ]
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: publish-to-conda
  #     uses: fcakyon/conda-publish-action@v1.3
  #     with:
  #       subdir: 'conda'
  #       anacondatoken: ${{ secrets.ANACONDA_TOKEN }}
  #       platforms: 'win osx linux'