name: Website vulnerability scan

on:
  workflow_dispatch:
  # schedule:
  #   - cron:  '00 03 * * *'
  # Everyday at 03:00 am

jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scan-website: ['https://openpredict.semanticscience.org/']
    steps:
    - name: ZAP Scan ${{ matrix.scan-website }}
      uses: zaproxy/action-baseline@v0.3.0
      # uses: zaproxy/action-full-scan@v0.1.0
      with:
        target: ${{ matrix.scan-website }}
        issue_title: ZAP Scan Baseline Report - ${{ matrix.scan-website }}
