name: Scan Docker image
on:
  workflow_dispatch:
  # push:
  #   branches: [ master ]
  #   paths:
  #   - 'requirements.txt'
  #   - 'Dockerfile'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --tag openpredict-api:latest
    - uses: anchore/scan-action@master
      with:
        image-reference: "openpredict-api:latest"
        dockerfile-path: "Dockerfile"
        # fail-build: true
    - name: anchore inline scan JSON results
      run: for j in `ls ./anchore-reports/*.json`; do echo "---- ${j} ----"; cat ${j}; echo; done